# Generated by Django 2.1.1 on 2018-09-15 18:20

import authentication.util
from django.db import migrations, models
import django.db.models.deletion
import djchoices.choices
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_on', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=2, null=True, validators=[djchoices.choices.ChoicesValidator({'F': 'Female', 'M': 'Male'})])),
                ('date_of_birth', models.DateField(blank=True, null=True, validators=[authentication.util.age_validator])),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('deleted_by', models.ForeignKey(blank=True, db_index=False, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_users', to='authentication.User')),
            ],
        ),
    ]
