# Generated by Django 2.1.1 on 2018-09-15 18:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('created_on', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='playlist_created_by', to='authentication.User')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('created_on', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislike', models.PositiveIntegerField(default=0)),
                ('subscribed', models.PositiveIntegerField(default=0)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('video_played', models.PositiveIntegerField(default=0)),
                ('deleted_by', models.ForeignKey(blank=True, db_index=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='video_delete_user', to='authentication.User')),
            ],
        ),
        migrations.CreateModel(
            name='VideoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_type', models.CharField(blank=True, choices=[('FUNNY', 'funny'), ('C', 'comedy')], db_index=True, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.ManyToManyField(blank=True, db_index=True, to='video.VideoType'),
        ),
        migrations.AddField(
            model_name='video',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='authentication.User'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='video',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='playlist', to='video.Video'),
        ),
    ]
