# Generated by Django 2.1.1 on 2018-09-16 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
